//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis_Otomasyonu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TeknikServisOtomasyonuEntities : DbContext
    {
        public TeknikServisOtomasyonuEntities()
            : base("name=TeknikServisOtomasyonuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_Admin> tbl_Admin { get; set; }
        public virtual DbSet<tbl_ArizaDetay> tbl_ArizaDetay { get; set; }
        public virtual DbSet<tbl_Cariler> tbl_Cariler { get; set; }
        public virtual DbSet<tbl_Departman> tbl_Departman { get; set; }
        public virtual DbSet<tbl_FaturaBilgi> tbl_FaturaBilgi { get; set; }
        public virtual DbSet<tbl_FaturaDetay> tbl_FaturaDetay { get; set; }
        public virtual DbSet<tbl_Giderler> tbl_Giderler { get; set; }
        public virtual DbSet<tbl_Kategori> tbl_Kategori { get; set; }
        public virtual DbSet<tbl_Notlar> tbl_Notlar { get; set; }
        public virtual DbSet<tbl_Personeller> tbl_Personeller { get; set; }
        public virtual DbSet<tbl_UrunHaraket> tbl_UrunHaraket { get; set; }
        public virtual DbSet<tbl_UrunKabul> tbl_UrunKabul { get; set; }
        public virtual DbSet<tbl_Urunler> tbl_Urunler { get; set; }
        public virtual DbSet<tbl_UrunTakip> tbl_UrunTakip { get; set; }
        public virtual DbSet<tbl_Hakkımızda> tbl_Hakkımızda { get; set; }
        public virtual DbSet<tbl_Iletisim> tbl_Iletisim { get; set; }
        public virtual DbSet<tbl_Ilce> tbl_Ilce { get; set; }
        public virtual DbSet<tbl_Iller> tbl_Iller { get; set; }
    
        public virtual ObjectResult<urunkategori_Result> urunkategori()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<urunkategori_Result>("urunkategori");
        }
    
        public virtual ObjectResult<string> makskategoriurun()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("makskategoriurun");
        }
    
        public virtual ObjectResult<string> maksurunmarka()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("maksurunmarka");
        }
    }
}
