//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis_Otomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ArizaDetay
    {
        public int ArızaID { get; set; }
        public Nullable<int> Islem { get; set; }
        public string Sorun { get; set; }
        public string Aciklama { get; set; }
        public Nullable<decimal> OnFiyat { get; set; }
        public Nullable<decimal> NetFiyat { get; set; }
        public string Islemler { get; set; }
    }
}
