//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis_Otomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FaturaBilgi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_FaturaBilgi()
        {
            this.tbl_FaturaDetay = new HashSet<tbl_FaturaDetay>();
        }
    
        public int ID { get; set; }
        public string Seri { get; set; }
        public string SiraNo { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Saat { get; set; }
        public string VergiDaire { get; set; }
        public Nullable<int> Cari { get; set; }
        public Nullable<short> Personel { get; set; }
    
        public virtual tbl_Cariler tbl_Cariler { get; set; }
        public virtual tbl_Personeller tbl_Personeller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_FaturaDetay> tbl_FaturaDetay { get; set; }
    }
}
